version: '3.4'
services: 

  nginx:
    build:
      dockerfile: ./docker/nginx.Dockerfile
      context: .
    image: raelamorim/nginx
    container_name: nginx
    ports: 
      - "80:80"
    networks: 
      - prod
    depends_on:
      - "app1"
      - "app2" 
      - "app3"
      - "redis"
      - "mysql"

  app1:
    build:
      dockerfile: ./docker/gonoticias.Dockerfile
      context: .
    image: golang
    container_name: app1
    ports:
      - "8080"
    networks:
      - prod
    depends_on:
      - "mysql"
      - "redis"

  app2:
    build:
      dockerfile: ./docker/gonoticias.Dockerfile
      context: .
    image: golang
    container_name: app2
    ports:
      - "8080"
    networks:
      - prod
    depends_on:
      - "mysql"
      - "redis"

  app3:
    build:
      dockerfile: ./docker/gonoticias.Dockerfile
      context: .
    image: golang
    container_name: app3
    ports:
      - "8080"
    networks:
      - prod
    depends_on:
      - "mysql"
      - "redis"

  redis:
    image: redis
    container_name: redis
    networks:
      - prod
    depends_on:
      - mysql

  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

networks:
  prod:
    driver: bridge